<?php

namespace App\Utils;

class Constants
{
    const PROPERTY_DOC_FOLDER = 'documents';
    const APARTMENT_DOC_FOLDER = 'apartment/documents';
    const DAMAGE_DOC_FOLDER = 'tickets';
    const DAMAGE_NAME_PREFIX = 'Ticket #';
    const MESSAGE_DOC_FOLDER = 'messages';
    const DEFAULT_MAX_RESULT_COUNT = false;
    const DIRECTORY_TYPES = ['individual', 'company', 'property_admin', 'janitor', 'users', 'people'];
    const FAVOURITES_ROLES = ['individual', 'company', 'property_admin'];
    const OBJECT_CONTRACT_TYPE_RENTAL = 0;
    const OBJECT_CONTRACT_TYPE_OWNER = 1;
    const DOC_TYPES = ['property', 'apartment', 'contract', 'coverImage', 'floorPlan'];
    const TYPE_INDIVIDUAL = 'individual';
    const USER_ROLES = ['individual', 'company', 'property_admin', 'janitor', 'tenant', 'object_owner'];
    const LANGUAGE_CODES = ['en', 'de'];
    const INHERITED_ROLES = ['company_user' => 'company', 'property_admin' => 'owner'];
    const STATUS = [
        'confirm_repair_status' => 'REPAIR_CONFIRMED',
        'damage_status' =>
            [
                'OWNER_CREATE_DAMAGE' => 'OWNER_CREATE_DAMAGE',
                'TENANT_CREATE_DAMAGE' => 'TENANT_CREATE_DAMAGE',
                'OBJECT_OWNER_CREATE_DAMAGE' => 'OBJECT_OWNER_CREATE_DAMAGE',
                'OWNER_SEND_TO_COMPANY_WITH_OFFER' => 'OWNER_SEND_TO_COMPANY_WITH_OFFER',
                'OWNER_SEND_TO_COMPANY_WITHOUT_OFFER' => 'OWNER_SEND_TO_COMPANY_WITHOUT_OFFER',
                'TENANT_SEND_TO_COMPANY_WITH_OFFER' => 'TENANT_SEND_TO_COMPANY_WITH_OFFER',
                'TENANT_SEND_TO_COMPANY_WITHOUT_OFFER' => 'TENANT_SEND_TO_COMPANY_WITHOUT_OFFER',
                'COMPANY_SCHEDULE_DATE' => 'COMPANY_SCHEDULE_DATE',
                'COMPANY_GIVE_OFFER_TO_OWNER' => 'COMPANY_GIVE_OFFER_TO_OWNER',
                'COMPANY_GIVE_OFFER_TO_TENANT' => 'COMPANY_GIVE_OFFER_TO_TENANT',
                'OWNER_REJECT_DAMAGE' => 'OWNER_REJECT_DAMAGE',
                'DEFECT_RAISED' => 'DEFECT_RAISED',
                'OWNER_REJECTS_THE_OFFER' => 'OWNER_REJECTS_THE_OFFER',
                'TENANT_REJECTS_THE_OFFER' => 'TENANT_REJECTS_THE_OFFER',
                'COMPANY_REJECT_THE_DAMAGE' => 'COMPANY_REJECT_THE_DAMAGE',
                'COMPANY_ACCEPTS_DAMAGE_WITHOUT_OFFER' => 'COMPANY_ACCEPTS_DAMAGE_WITHOUT_OFFER',
            ]
    ];
    const COMPANY_REJECT_THE_DAMAGE = 'COMPANY_REJECT_THE_DAMAGE';
    const COMPANY_ACCEPT_THE_DAMAGE = 'COMPANY_ACCEPTS_DAMAGE_WITHOUT_OFFER';
    const DEFAULT_LOCALE = 'de';
    const RENTAL_TYPE_OPENEND = 'open-end';
    const RENTAL_TYPE_FIXED = 'fixed-term';
    const RENTAL_TYPE_TERMINATED = 'terminated';
    const RENTAL_TYPE_FUTURE = 'future';
    const ALLOWED_DOC_TYPES = [
        'application/pdf' => 'pdf',
        'image/png' => 'png',
        'image/jpeg' => 'jpg',
        'image/jpg' => 'jpg',
        'application/msword' => 'doc',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document' => 'docx',
        'application/vnd.ms-excel' => 'xls'
    ];
    const DATE_TIME_FORMAT = 'Y-m-d H:i';
    const TYPE_NOTICE_PERIOD_1_MONTH = 30;
    const TYPE_NOTICE_PERIOD_3_MONTH = 90;
    const TYPE_NOTICE_PERIOD_6_MONTH = 180;
    const MESSAGE_TYPE = [1 => 'ticket', 2 => 'question', 3 => 'information'];
    const CONTRACT_STATUS_ARCHIVED = 0;
    const CONTRACT_STATUS_ACTIVE = 1;
    const CONTRACT_STATUS_TERMINATED = 2;
    const CONTRACT_STATUS_FUTURE = 3;
    const CONTRACT_STATUSES = ['archived', 'active', 'terminated', 'future'];
    const BOOLEAN = [0 => false, 1 => true];
    const EXCEPTED_MIME_TYPES = [
        'application/x-pdf',
        'application/pdf',
        'application/msword' => 'doc',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document' => 'docx',
        'application/vnd.ms-excel' => 'xls'
    ];
    const MIN_SEARCH_CHARACHERS = 3;
    const DISPLAY_ID_FORMAT = '%03d';
    const TENANT_ROLE = 'tenant';
    const OBJECT_OWNER_ROLE = 'objectOwner';
    const ADMIN_ROLE = 'admin';
    const PROPERTY_ADMIN_ROLE = 'propertyAdmin';
    const JANITOR_ROLE = 'janitor';
    const COMPANY_ROLE = 'company';
    const COMPANY_USER_ROLE = 'companyUser';
    const OWNER_ROLE = 'owner';
    const GUEST_ROLE = 'guest';
    const INDIVIDUAL = 'individual';
    const ROLE_GUEST = 'ROLE_GUEST';
    const ROLE_ADMIN = 'ROLE_ADMIN';
    const CHECK_ALLOCATION_TYPE_OPEN_DAMAGES = [
        'TENANT_CREATE_DAMAGE',
        'OBJECT_OWNER_CREATE_DAMAGE',
        'OWNER_ACCEPTS_DAMAGE',
        'PROPERTY_ADMIN_ACCEPTS_DAMAGE',
        'OWNER_SEND_TO_COMPANY_WITHOUT_OFFER',
        'JANITOR_SEND_TO_COMPANY_WITHOUT_OFFER',
        'JANITOR_SEND_TO_COMPANY_WITH_OFFER',
        'PROPERTY_ADMIN_SEND_TO_COMPANY_WITH_OFFER',
        'PROPERTY_ADMIN_SEND_TO_COMPANY_WITHOUT_OFFER',
        'COMPANY_GIVE_OFFER_TO_PROPERTY_ADMIN',
        'COMPANY_GIVE_OFFER_TO_OWNER',
        'COMPANY_SCHEDULE_DATE',
        'OBJECT_OWNER_REJECTS_DATE',
        'PROPERTY_ADMIN_REJECTS_DATE',
        'OWNER_REJECTS_DATE',
        'OWNER_ACCEPTS_THE_OFFER',
        'TENANT_ACCEPTS_THE_OFFER',
        'OBJECT_OWNER_ACCEPTS_THE_OFFER',
        'PROPERTY_ADMIN_ACCEPTS_THE_OFFER',
        'PROPERTY_ADMIN_ACCEPTS_DATE',
        'OWNER_ACCEPTS_DATE',
        'TENANT_ACCEPTS_DATE',
        'OBJECT_OWNER_ACCEPTS_DATE',
        'REPAIR_CONFIRMED',
        'TENANT_REJECTS_DATE',
        'DEFECT_RAISED',
        'JANITOR_CREATE_DAMAGE',
        'JANITOR_ACCEPTS_DAMAGE',
        'JANITOR_SEND_TO_COMPANY_WITHOUT_OFFER',
        'COMPANY_GIVE_OFFER_TO_JANITOR',
        'JANITOR_ACCEPTS_THE_OFFER',
        'JANITOR_ACCEPTS_DATE',
        'JANITOR_REJECTS_DATE'
    ];
    const ROLE_COLOUR = [
        'company' => 'rgb(255 233 136)',
        'owner' => 'rgb(242, 101, 34)',
        'propertyAdmin' => 'rgb(242, 207, 34)',
        'janitor' => 'rgb(113, 113, 113)',
        'objectOwner' => 'rgb(193 165 26)',
        'tenant' => 'rgb(184 74 22)',
        'user' => 'rgb(242, 101, 34)'
    ];
    const CLOSE_DAMAGES = [
        'TENANT_CLOSE_THE_DAMAGE',
        'OWNER_CLOSE_THE_DAMAGE',
        'JANITOR_CLOSE_THE_DAMAGE',
        'OBJECT_OWNER_CLOSE_THE_DAMAGE',
        'PROPERTY_ADMIN_CLOSE_THE_DAMAGE',
        'JANITOR_CLOSE_THE_DAMAGE'
    ];
    const ACCEPT_DAMAGES = [
        'OWNER_ACCEPTS_THE_OFFER',
        'TENANT_ACCEPTS_THE_OFFER',
        'OBJECT_OWNER_ACCEPTS_THE_OFFER',
        'PROPERTY_ADMIN_ACCEPTS_THE_OFFER',
        'JANITOR_ACCEPTS_THE_OFFER'
    ];
    const OPEN_DAMAGES_FOR_OWNER_AND_ADMIN = [
        'OWNER_CREATE_DAMAGE',
        'OWNER_REJECTS_DATE',
        'OWNER_ACCEPTS_DAMAGE',
        'OWNER_SEND_TO_COMPANY_WITH_OFFER',
        'PROPERTY_ADMIN_CREATE_DAMAGE',
        'PROPERTY_ADMIN_ACCEPTS_DAMAGE',
        'OWNER_SEND_TO_COMPANY_WITHOUT_OFFER',
        'OWNER_REJECTS_THE_OFFER',
        'REPAIR_CONFIRMED',
        'OWNER_SEND_TO_COMPANY_WITH_OFFER',
        'OWNER_SEND_TO_COMPANY_WITHOUT_OFFER',
        'PROPERTY_ADMIN_SEND_TO_COMPANY_WITH_OFFER',
        'PROPERTY_ADMIN_SEND_TO_COMPANY_WITHOUT_OFFER',
        'COMPANY_GIVE_OFFER_TO_PROPERTY_ADMIN',
        'COMPANY_SCHEDULE_DATE',
        'OWNER_ACCEPTS_DATE',
        'PROPERTY_ADMIN_ACCEPTS_THE_OFFER',
        'COMPANY_GIVE_OFFER_TO_OWNER',
        'OWNER_ACCEPTS_THE_OFFER',
        'DEFECT_RAISED',
        'REPAIR_CONFIRMED',
        'PROPERTY_ADMIN_ACCEPTS_DATE',
        'PROPERTY_ADMIN_REJECTS_DATE',
        'JANITOR_CREATE_DAMAGE',
        'JANITOR_ACCEPTS_DAMAGE',
        'JANITOR_SEND_TO_COMPANY_WITHOUT_OFFER',
        'COMPANY_GIVE_OFFER_TO_JANITOR',
        'JANITOR_ACCEPTS_THE_OFFER',
        'JANITOR_ACCEPTS_DATE',
        'JANITOR_REJECTS_DATE'
    ];
    const OPEN_DAMAGES_FOR_TENANT_AND_OBJECT_OWNER = [
        'OWNER_ACCEPTS_DAMAGE',
        'PROPERTY_ADMIN_ACCEPTS_DAMAGE',
        'PROPERTY_ADMIN_REJECTS_DATE',
        'TENANT_CREATE_DAMAGE',
        'OBJECT_OWNER_CREATE_DAMAGE',
        'JANITOR_CREATE_DAMAGE',
        'OWNER_SEND_TO_COMPANY_WITH_OFFER',
        'OWNER_SEND_TO_COMPANY_WITHOUT_OFFER',
        'REPAIR_CONFIRMED',
        'PROPERTY_ADMIN_REJECT_DAMAGE',
        'OWNER_REJECT_DAMAGE',
        'TENANT_SEND_TO_COMPANY_WITH_OFFER',
        'TENANT_SEND_TO_COMPANY_WITHOUT_OFFER',
        'TENANT_REJECTS_THE_OFFER',
        'TENANT_REJECTS_DATE',
        'TENANT_ACCEPTS_THE_OFFER',
        'TENANT_ACCEPTS_DATE',
        'OWNER_ACCEPTS_THE_OFFER',
        'OWNER_ACCEPTS_DATE',
        'COMPANY_SCHEDULE_DATE',
        'COMPANY_GIVE_OFFER_TO_TENANT',
        'COMPANY_GIVE_OFFER_TO_OWNER',
        'COMPANY_ACCEPTS_DAMAGE_WITH_OFFER',
        'COMPANY_ACCEPTS_DAMAGE_WITHOUT_OFFER',
        'PROPERTY_ADMIN_SEND_TO_COMPANY_WITH_OFFER',
        'PROPERTY_ADMIN_SEND_TO_COMPANY_WITHOUT_OFFER',
        'COMPANY_GIVE_OFFER_TO_PROPERTY_ADMIN',
        'PROPERTY_ADMIN_ACCEPTS_THE_OFFER',
        'PROPERTY_ADMIN_REJECTS_THE_OFFER',
        'PROPERTY_ADMIN_ACCEPTS_DATE',
        'PROPERTY_ADMIN_REJECTS_DATE',
        'OBJECT_OWNER_SEND_TO_COMPANY_WITH_OFFER',
        'OBJECT_OWNER_SEND_TO_COMPANY_WITHOUT_OFFER',
        'COMPANY_GIVE_OFFER_TO_OBJECT_OWNER',
        'OBJECT_OWNER_ACCEPTS_THE_OFFER',
        'OBJECT_OWNER_REJECTS_THE_OFFER',
        'OBJECT_OWNER_ACCEPTS_DATE',
        'OBJECT_OWNER_REJECTS_DATE',
        'DEFECT_RAISED',
        'PROPERTY_ADMIN_ACCEPTS_DAMAGE',
        'JANITOR_ACCEPTS_DAMAGE',
        'JANITOR_SEND_TO_COMPANY_WITHOUT_OFFER',
        'JANITOR_SEND_TO_COMPANY_WITH_OFFER',
        'JANITOR_ACCEPTS_THE_OFFER',
        'JANITOR_REJECT_DAMAGE'
    ];
    const OPEN_DAMAGES_FOR_COMPANY_AND_COMPANY_USER_ROLE = [
        'OWNER_SEND_TO_COMPANY_WITH_OFFER',
        'OWNER_SEND_TO_COMPANY_WITHOUT_OFFER',
        'OWNER_REJECTS_THE_OFFER',
        'REPAIR_CONFIRMED',
        'TENANT_SEND_TO_COMPANY_WITH_OFFER',
        'TENANT_SEND_TO_COMPANY_WITHOUT_OFFER',
        'TENANT_REJECTS_THE_OFFER',
        'TENANT_REJECTS_DATE',
        'OWNER_REJECTS_DATE',
        'TENANT_ACCEPTS_THE_OFFER',
        'TENANT_ACCEPTS_DATE',
        'OWNER_ACCEPTS_THE_OFFER',
        'OWNER_ACCEPTS_DATE',
        'COMPANY_SCHEDULE_DATE',
        'COMPANY_GIVE_OFFER_TO_TENANT',
        'COMPANY_GIVE_OFFER_TO_OWNER',
        'COMPANY_ACCEPTS_DAMAGE_WITH_OFFER',
        'COMPANY_ACCEPTS_DAMAGE_WITHOUT_OFFER',
        'PROPERTY_ADMIN_SEND_TO_COMPANY_WITH_OFFER',
        'PROPERTY_ADMIN_SEND_TO_COMPANY_WITHOUT_OFFER',
        'COMPANY_GIVE_OFFER_TO_PROPERTY_ADMIN',
        'PROPERTY_ADMIN_ACCEPTS_THE_OFFER',
        'PROPERTY_ADMIN_REJECTS_THE_OFFER',
        'PROPERTY_ADMIN_ACCEPTS_DATE',
        'PROPERTY_ADMIN_REJECTS_DATE',
        'OBJECT_OWNER_SEND_TO_COMPANY_WITH_OFFER',
        'OBJECT_OWNER_SEND_TO_COMPANY_WITHOUT_OFFER',
        'COMPANY_GIVE_OFFER_TO_OBJECT_OWNER',
        'OBJECT_OWNER_ACCEPTS_THE_OFFER',
        'OBJECT_OWNER_REJECTS_THE_OFFER',
        'OBJECT_OWNER_ACCEPTS_DATE',
        'OBJECT_OWNER_REJECTS_DATE',
        'DEFECT_RAISED',
        'JANITOR_SEND_TO_COMPANY_WITH_OFFER',
        'JANITOR_SEND_TO_COMPANY_WITHOUT_OFFER',
        'COMPANY_GIVE_OFFER_TO_JANITOR',
        'JANITOR_ACCEPTS_THE_OFFER',
        'JANITOR_REJECTS_THE_OFFER',
        'JANITOR_ACCEPTS_DATE',
        'JANITOR_REJECTS_DATE',
        'JANITOR_CLOSE_THE_DAMAGE'
    ];

    const COUNT_OPEN_DAMAGES_FOR_COMPANY_AND_COMPANY_USER_ROLE = [
        'OWNER_SEND_TO_COMPANY_WITH_OFFER',
        'OWNER_SEND_TO_COMPANY_WITHOUT_OFFER',
        'OWNER_REJECTS_THE_OFFER',
        'REPAIR_CONFIRMED',
        'TENANT_SEND_TO_COMPANY_WITH_OFFER',
        'TENANT_SEND_TO_COMPANY_WITHOUT_OFFER',
        'TENANT_REJECTS_THE_OFFER',
        'TENANT_REJECTS_DATE',
        'TENANT_ACCEPTS_THE_OFFER',
        'TENANT_ACCEPTS_DATE',
        'OWNER_ACCEPTS_THE_OFFER',
        'OWNER_ACCEPTS_DATE',
        'COMPANY_SCHEDULE_DATE',
        'COMPANY_ACCEPTS_DAMAGE_WITH_OFFER',
        'COMPANY_ACCEPTS_DAMAGE_WITHOUT_OFFER',
        'PROPERTY_ADMIN_SEND_TO_COMPANY_WITH_OFFER',
        'PROPERTY_ADMIN_SEND_TO_COMPANY_WITHOUT_OFFER',
        'COMPANY_GIVE_OFFER_TO_PROPERTY_ADMIN',
        'PROPERTY_ADMIN_ACCEPTS_THE_OFFER',
        'PROPERTY_ADMIN_REJECTS_THE_OFFER',
        'PROPERTY_ADMIN_ACCEPTS_DATE',
        'PROPERTY_ADMIN_REJECTS_DATE',
        'OBJECT_OWNER_SEND_TO_COMPANY_WITH_OFFER',
        'OBJECT_OWNER_SEND_TO_COMPANY_WITHOUT_OFFER',
        'COMPANY_GIVE_OFFER_TO_OBJECT_OWNER',
        'OBJECT_OWNER_ACCEPTS_THE_OFFER',
        'OBJECT_OWNER_REJECTS_THE_OFFER',
        'OBJECT_OWNER_ACCEPTS_DATE',
        'OBJECT_OWNER_REJECTS_DATE',
        'DEFECT_RAISED',
        'JANITOR_SEND_TO_COMPANY_WITH_OFFER',
        'JANITOR_SEND_TO_COMPANY_WITHOUT_OFFER',
        'COMPANY_GIVE_OFFER_TO_JANITOR',
        'JANITOR_ACCEPTS_THE_OFFER',
        'JANITOR_REJECTS_THE_OFFER',
        'JANITOR_ACCEPTS_DATE',
        'JANITOR_REJECTS_DATE',
        'JANITOR_CLOSE_THE_DAMAGE'
    ];

    const ALLOCATION_OWNER_OR_ADMIN = true;
    const ALLOCATION_MYSELF = false;
    const SYSTEM_GENERATED_OBJECT = 'General/Environment';
    const SYSTEM_GENERATED_OBJECT_DE = 'Allgemein / Umgebung';
    const ADMIN_NO_REDIRECTION_EVENTS = ['ADMINISTRATIVE_INVITE_REJECTED', 'ADMINISTRATIVE_INVITE_ACCEPTED'];
    const SUPER_ADMIN_MASTER_DATA_TYPES = ['floor', 'landIndex', 'objectType', 'referenceIndex'];
    const MASTER_DATA_KEY_FLOOR = 'floor';
    const MASTER_DATA_KEY_LAND_INDEX = 'landIndex';
    const MASTER_DATA_KEY_OBJECT_TYPE = 'objectType';
    const MASTER_DATA_KEY_REFERENCE_TYPE = 'referenceIndex';
    const LOG_COMPANY_GIVE_OFFER = ['COMPANY_GIVE_OFFER_TO_OWNER', 'COMPANY_GIVE_OFFER_TO_PROPERTY_ADMIN', 'COMPANY_GIVE_OFFER_TO_JANITOR'];
    const LOG_DAMAGE_CREATE = ['TENANT_CREATE_DAMAGE', 'OBJECT_OWNER_CREATE_DAMAGE', 'JANITOR_CREATE_DAMAGE'];
    const LOG_DAMAGE_ACCEPT = ['OWNER_ACCEPTS_DAMAGE', 'PROPERTY_ADMIN_ACCEPTS_DAMAGE', 'JANITOR_ACCEPTS_DAMAGE'];
    const LOG_DAMAGE_SEND_TO_COMPANY = ['OWNER_SEND_TO_COMPANY_WITHOUT_OFFER', 'PROPERTY_ADMIN_SEND_TO_COMPANY_WITHOUT_OFFER', 'JANITOR_SEND_TO_COMPANY_WITHOUT_OFFER'];
    const LOG_DAMAGE_COMPANY_OFFER_ACCEPT = ['OWNER_ACCEPTS_THE_OFFER', 'PROPERTY_ADMIN_ACCEPTS_THE_OFFER', 'JANITOR_ACCEPTS_THE_OFFER'];
    const LOG_DAMAGE_COMPANY_SCHEDULE_DATE = ['COMPANY_SCHEDULE_DATE'];
    const LOG_DAMAGE_CLOSE = ['TENANT_CLOSE_THE_DAMAGE', 'OBJECT_OWNER_CLOSE_THE_DAMAGE'];
    const LOG_DAMAGE_SEND_TO_COMPANY_BY_PRIVATE = ['TENANT_SEND_TO_COMPANY_WITHOUT_OFFER', 'OBJECT_OWNER_SEND_TO_COMPANY_WITHOUT_OFFER'];
    const LOG_COMPANY_GIVE_OFFER_TO_PRIVATE = ['COMPANY_GIVE_OFFER_TO_TENANT', 'COMPANY_GIVE_OFFER_TO_OBJECT_OWNER'];
    const LOG_DAMAGE_COMPANY_OFFER_ACCEPT_BY_PRIVATE = ['TENANT_ACCEPTS_THE_OFFER', 'OBJECT_OWNER_ACCEPTS_THE_OFFER'];
    const LOG_REPAIR_CONFIRM_ADMIN_WORKFLOW = ['owner', 'property_admin', 'janitor'];
    const LOG_REPAIR_CONFIRM_TENANT_WORKFLOW = ['tenant', 'object_owner'];
    const LOG_DAMAGE_CREATE_BY_ADMIN_OR_OWNER_PRIVATE = ['OWNER_CREATE_DAMAGE', 'PROPERTY_ADMIN_CREATE_DAMAGE', 'JANITOR_CREATE_DAMAGE'];
    const LOG_DAMAGE_CLOSE_BY_ADMIN_OR_OWNER = ['PROPERTY_ADMIN_CLOSE_THE_DAMAGE', 'OWNER_CLOSE_THE_DAMAGE', 'JANITOR_CLOSE_THE_DAMAGE'];
    const LOG_DAMAGE_REPAIR_COMPLETED = ['REPAIR_CONFIRMED'];
    const LOG_DAMAGE_DEFECT_RAISED = ['DEFECT_RAISED'];
    const LOG_DAMAGE_CONFIRM_ACCEPT_DATE = ['OWNER_ACCEPTS_DATE', 'TENANT_ACCEPTS_DATE', 'PROPERTY_ADMIN_ACCEPTS_DATE', 'JANITOR_ACCEPTS_DATE', 'OBJECT_OWNER_ACCEPTS_DATE'];
    const LOG_DAMAGE_REJECTS_DATE = ['PROPERTY_ADMIN_REJECTS_DATE', 'TENANT_REJECTS_DATE', 'OWNER_REJECTS_DATE', 'JANITOR_REJECTS_DATE', 'OBJECT_OWNER_REJECTS_DATE'];
    const CHAT_DISABLE_DAMAGE_STATUS = [
        'TENANT_CREATE_DAMAGE',
        'OBJECT_OWNER_CREATE_DAMAGE',
        'OWNER_REJECT_DAMAGE',
        'PROPERTY_ADMIN_REJECT_DAMAGE',
        'TENANT_SEND_TO_COMPANY_WITHOUT_OFFER',
        'OBJECT_OWNER_SEND_TO_COMPANY_WITHOUT_OFFER',
        'JANITOR_REJECT_DAMAGE'
    ];
    const ADDRESSABLE_DAMAGE_FOR_OWNER_OR_ADMIN_FROM_OBJECT_OWNER_OR_TENANT = [
        'TENANT_CREATE_DAMAGE',
        'OBJECT_OWNER_CREATE_DAMAGE'
    ];

    const ADDRESSABLE_REQUEST_STATUES = [
        'COMPANY_GIVE_OFFER_TO_OWNER',
        'COMPANY_GIVE_OFFER_TO_PROPERTY_ADMIN',
        'COMPANY_REJECT_THE_DAMAGE'
    ];
    const ADDRESSABLE_OWNER_OR_ADMIN_ACCEPTANCE = [
        'OWNER_ACCEPTS_OFFER',
        'PROPERTY_ADMIN_ACCEPTS_OFFER',
        'PROPERTY_ADMIN_REJECT_DAMAGE',
        'OWNER_REJECT_DAMAGE',
        'JANITOR_REJECT_DAMAGE'
    ];
    const ADDRESSABLE_DAMAGE_FOR_OWNER_OR_ADMIN = [
        'OWNER_CREATE_DAMAGE',
        'OWNER_ACCEPTS_DAMAGE',
        'JANITOR_CREATE_DAMAGE',
        'PROPERTY_ADMIN_CREATE_DAMAGE',
        'PROPERTY_ADMIN_ACCEPTS_DAMAGE',
        'REPAIR_CONFIRMED',
        'COMPANY_GIVE_OFFER_TO_PROPERTY_ADMIN',
        'COMPANY_SCHEDULE_DATE',
        'PROPERTY_ADMIN_ACCEPTS_THE_OFFER',
        'COMPANY_GIVE_OFFER_TO_OWNER',
        'COMPANY_REJECT_THE_DAMAGE'
    ];

    const ADDRESSABLE_DAMAGE_FOR_TENANT = [
        'TENANT_CREATE_DAMAGE',
        'OWNER_REJECT_DAMAGE',
        'PROPERTY_ADMIN_REJECT_DAMAGE',
        'COMPANY_SCHEDULE_DATE',
        'COMPANY_GIVE_OFFER_TO_TENANT',
        'TENANT_ACCEPTS_THE_OFFER',
        'JANITOR_REJECT_DAMAGE'
    ];
    const ADDRESSABLE_DAMAGE_FOR_OBJECT_OWNER = [
        'OBJECT_OWNER_CREATE_DAMAGE',
        'COMPANY_GIVE_OFFER_TO_OBJECT_OWNER',
        'REPAIR_CONFIRMED',
        'COMPANY_SCHEDULE_DATE',
        'OWNER_REJECT_DAMAGE',
        'PROPERTY_ADMIN_REJECT_DAMAGE',
        'OBJECT_OWNER_ACCEPTS_THE_OFFER',
        'JANITOR_REJECT_DAMAGE'
    ];
    const ADDRESSABLE_DAMAGE_FOR_COMPANIES = [
        'TENANT_REJECTS_THE_OFFER',
        'TENANT_REJECTS_DATE',
        'TENANT_ACCEPTS_THE_OFFER',
        'TENANT_ACCEPTS_DATE',
        'TENANT_SEND_TO_COMPANY_WITH_OFFER',
        'TENANT_SEND_TO_COMPANY_WITHOUT_OFFER',
        'OWNER_SEND_TO_COMPANY_WITH_OFFER',
        'OWNER_SEND_TO_COMPANY_WITHOUT_OFFER',
        'OWNER_REJECTS_THE_OFFER',
        'OWNER_REJECTS_DATE',
        'OWNER_ACCEPTS_THE_OFFER',
        'OWNER_ACCEPTS_DATE',
        'DEFECT_RAISED',
        'COMPANY_ACCEPTS_DAMAGE_WITH_OFFER',
        'COMPANY_ACCEPTS_DAMAGE_WITHOUT_OFFER',
        'PROPERTY_ADMIN_SEND_TO_COMPANY_WITH_OFFER',
        'PROPERTY_ADMIN_SEND_TO_COMPANY_WITHOUT_OFFER',
        'PROPERTY_ADMIN_ACCEPTS_THE_OFFER',
        'PROPERTY_ADMIN_ACCEPTS_DATE',
        'PROPERTY_ADMIN_REJECTS_DATE',
        'JANITOR_SEND_TO_COMPANY_WITH_OFFER',
        'JANITOR_SEND_TO_COMPANY_WITHOUT_OFFER',
        'JANITOR_ACCEPTS_THE_OFFER',
        'JANITOR_REJECTS_THE_OFFER',
        'JANITOR_ACCEPTS_DATE',
        'JANITOR_REJECTS_DATE',
        'OBJECT_OWNER_SEND_TO_COMPANY_WITH_OFFER',
        'OBJECT_OWNER_SEND_TO_COMPANY_WITHOUT_OFFER',
        'OBJECT_OWNER_ACCEPTS_THE_OFFER',
        'OBJECT_OWNER_REJECTS_THE_OFFER',
        'OBJECT_OWNER_ACCEPTS_DATE',
        'OBJECT_OWNER_REJECTS_DATE'
    ];
    const CONTRACT_TYPE_OWNERSHIP = 'ownership';
    const CONTRACT_TYPE_RENTAL = 'rental';
    const PROPERTY_ACTIVE = 'active';
    const PROPERTY_INACTIVE = 'inactive';
    const PROPERTY_SUBSCRIPTION_CANCELLED = 'cancelled';
    const PROPERTY_SUBSCRIPTION_EXPIRED = 'expired';
    const TENANT_CREATED_OWNER_RESPONSIBLE_STATUS = [
        'TENANT_CREATE_DAMAGE',
        'OBJECT_OWNER_CREATE_DAMAGE',
        'OWNER_ACCEPTS_DAMAGE',
        'PROPERTY_ADMIN_ACCEPTS_DAMAGE'
    ];
    const ADDRESSABLE_DAMAGE_FOR_COMPANIES_AGAINST_OFFER = [
        'TENANT_REJECTS_THE_OFFER',
        'TENANT_REJECTS_DATE',
        'TENANT_ACCEPTS_THE_OFFER',
        'TENANT_ACCEPTS_DATE',
        'OWNER_REJECTS_THE_OFFER',
        'OWNER_REJECTS_DATE',
        'OWNER_ACCEPTS_THE_OFFER',
        'OWNER_ACCEPTS_DATE',
        'DEFECT_RAISED',
        'COMPANY_ACCEPTS_DAMAGE_WITH_OFFER',
        'COMPANY_ACCEPTS_DAMAGE_WITHOUT_OFFER',
        'PROPERTY_ADMIN_ACCEPTS_THE_OFFER',
        'PROPERTY_ADMIN_ACCEPTS_DATE',
        'PROPERTY_ADMIN_REJECTS_DATE',
        'JANITOR_ACCEPTS_THE_OFFER',
        'JANITOR_REJECTS_THE_OFFER',
        'JANITOR_ACCEPTS_DATE',
        'JANITOR_REJECTS_DATE',
        'OBJECT_OWNER_ACCEPTS_THE_OFFER',
        'OBJECT_OWNER_REJECTS_THE_OFFER',
        'OBJECT_OWNER_ACCEPTS_DATE',
        'OBJECT_OWNER_REJECTS_DATE',
        'PROPERTY_ADMIN_SEND_TO_COMPANY_WITH_OFFER',
        'PROPERTY_ADMIN_SEND_TO_COMPANY_WITHOUT_OFFER',
        'OWNER_SEND_TO_COMPANY_WITH_OFFER',
        'OWNER_SEND_TO_COMPANY_WITHOUT_OFFER',
        'TENANT_SEND_TO_COMPANY_WITH_OFFER',
        'TENANT_SEND_TO_COMPANY_WITHOUT_OFFER',
        'OBJECT_OWNER_SEND_TO_COMPANY_WITH_OFFER',
        'OBJECT_OWNER_SEND_TO_COMPANY_WITHOUT_OFFER'
    ];
    const OPEN_ADDRESSABLE_DAMAGES_FOR_OWNER_AND_ADMIN = [
        'COMPANY_GIVE_OFFER_TO_OWNER',
        'COMPANY_GIVE_OFFER_TO_PROPERTY_ADMIN'
    ];
    const DAMAGES_TO_BE_ADDRESSED_BY_OWNER_OR_ADMIN_ON_COMPANY_ACTION = [
        'COMPANY_GIVE_OFFER_TO_OWNER',
        'COMPANY_GIVE_OFFER_TO_PROPERTY_ADMIN',
        'COMPANY_REJECT_THE_DAMAGE'
    ];
    const EXCLUDED_DAMAGE_REQUEST_STATUS = [
        'COMPANY_REJECT_THE_DAMAGE',
        'OWNER_SEND_TO_COMPANY_WITH_OFFER',
        'OWNER_SEND_TO_COMPANY_WITHOUT_OFFER'
    ];
    const ADMINISTRATIVE_INVITE_EVENT = 'ADMINISTRATIVE_INVITE';
    const ADMINISTRATIVE_INVITE_ACCEPTED = 'ADMINISTRATIVE_INVITE_ACCEPTED';
    const ADMINISTRATIVE_INVITE_REJECTED = 'ADMINISTRATIVE_INVITE_REJECTED';
    const PROPERTY_ADMINISTRATIVE_INVITATION_ACCEPT_SUBJECT = 'PROPERTY_ADMINISTRATIVE_INVITATION_ACCEPT_SUBJECT';
    const PROPERTY_ADMINISTRATIVE_INVITATION_JANITOR_SUBJECT = 'PROPERTY_ADMINISTRATIVE_INVITATION_JANITOR_SUBJECT';
    const PROPERTY_JANITOR_INVITATION_ACCEPT_SUBJECT = 'PROPERTY_JANITOR_INVITATION_ACCEPT_SUBJECT';
    const PROPERTY_JANITOR_INVITATION_REJECT_SUBJECT = 'PROPERTY_JANITOR_INVITATION_REJECT_SUBJECT';
    const PROPERTY_ADMINISTRATIVE_INVITATION_REJECT_SUBJECT = 'PROPERTY_ADMINISTRATIVE_INVITATION_REJECT_SUBJECT';
    const REJECTED_DAMAGE_BY_OWNER_OR_ADMIN = ['OWNER_REJECT_DAMAGE', 'PROPERTY_ADMIN_REJECT_DAMAGE', 'JANITOR_REJECT_DAMAGE'];
    const OWNER_SEND_TO_COMPANY_WITHOUT_OFFER = 'OWNER_SEND_TO_COMPANY_WITHOUT_OFFER';
    const PROPERTY_ADMIN_SEND_TO_COMPANY_WITHOUT_OFFER = 'PROPERTY_ADMIN_SEND_TO_COMPANY_WITHOUT_OFFER';
    const JANITOR_PRESENT = 'janitorPresent';
    const JANITOR_INVITED = 'janitorInvited';
}